import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="font-sans">
        <div className="flex h-screen">
          {/* Sidebar */}
          <Sidebar />
          <div className="flex flex-col flex-1">
            {/* Topbar */}
            <Topbar />

            {/* Main Content */}
            <main>
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
